package it.ld.bw.info;

public enum AnimatedStaticInfo {
	NORS_GATE,
	GATE_STONE_PLINTH,
	PIPER_CAVE_ENTRANCE,
	CHESS_PION_TEAMA,
	CHESS_PION_TEAMB,
	CHESS_TOWER_TEAMA,
	CHESS_TOWER_TEAMB,
	CHESS_KNIGHT_TEAMA,
	CHESS_KNIGHT_TEAMB,
	CHESS_MAD_TEAMA,
	CHESS_MAD_TEAMB,
	CHESS_QUEEN_TEAMA,
	CHESS_QUEEN_TEAMB,
	CHESS_KING_TEAMA,
	CHESS_KING_TEAMB,
	PHONE_BOX;
}
