/* Copyright (c) 2026 Daniele Lombardi / Daniels118 */
package it.ld.bw.info;

import java.io.IOException;
import it.ld.utils.EndianDataInputStream;
import it.ld.utils.EndianDataOutputStream;

public class GTownInfo extends GContainerInfo {
    public int townType;
    public int size;
    public int minHousesToSetup;
    public int maxHousesToSetup;
    public int maxSizeInCells;
    public int distance;
    public int split;
    public int aroundCitadelStartAngle;
    public int aroundCitadelStepAngle;
    public int aroundCitadelStartDistance;
    public int aroundCitadelEndDistance;
    public int townCentre;
    public int storagePit;
    public int percentFemale;
    public int processAbodeEvery;
    public int newBuildingEvery;
    public int[] profession = new int[8];
    public float happyFoodMultiplier;
    public float influence;
    public float numberOfDaysFoodInStoreToBeHappy;
    public float happyWoodPerBuildingSite;
    public int playtimeEvery;
    public float maxDistanceWallBeBuilt;
    public float beliefNeededForWonder;
    public float proportionDeadForGraveyard;
    public float playerInteactDecay;
    public float howImpressedWithFlyingThing;
    public float impressedWithFlyingThingRemovedAsSeen;
    public float impressedWithFlyingThingAddPerGameTurn;
    public float baseBeliefDesireValue;
    public float totalWoodNeededToStartBuilding;
    public float firstTimeDamageDoneAddition;
    public int totalScaffoldNeededToStartBuilding;
    public float builtPercentBeforeWhichYouCanAddScaffolds;
    public float beliefInNeutralPlayer;
    public float maxAlignmentChangePerGameTurnForDesires;
    public float[] storyInfluence = new float[5];
    public float maxForTimeWillWorkUntil;
    public float bedTimeMod;
    public float foodWantedMultiplier;
    public float minimumWoodForDesire;
    public float maximumWoodForDesire;
    public float numOfBuildingsForDesiredWood;
    public float relaxationMod;
    public float startingBeliefForCreatedTown;
    public int emptyTownAllowedThisManyVillagers;
    public float multiplierForAddingResourceToTown;
    public float multiplierForNonOwnerAddingResource;
    public int maxGameturnsForBeliefAfterRemovingFromStoragePit;
    public float footballMatchDuration;
    public float beliefForFooballMatch;
    public float thresholdToStartRepairing;
    public int gameTurnsAfterEmergencyVillagersReact;
    public int numSecondsToIgnoreCreature;
    public int numSecondsBeforeTownForgetsAboutCreature;
    public int maxDistanceForVillagersToGoToTheWorshipsite;
    public float minLifeForVillagersToGoToTheWorshipsite;
    public float consideredEvilIfMakingDisciplesAndDesireIsLessThan;
    public float consideredGoodIfMakingDisciplesAndDesireIsGreaterThan;
    public int numGameTurnsBetweenGettingBeliefForArtifacts;
    public float populationForUnmodifiedBelief;
    public float multiplierForBeliefFromVillagersDancingAroundArtifact;
    public float giveResourceAligmnetChangeMultiplier;
    public float takeResourceAligmnetChangeMultiplier;
    public float maxDistanceFromCongreationPosThatPeopleChillOut;
    public float maxDistanceFromHouseThatPeopleChillOut;
    public float maxDistanceThatVillagersWillGoToWorship;
    public float amountOverCapacityThatDiscipleBreedersBreedUntil;
    public int populationUnderWhichHelpSpritesWarn;
    public float oneOffBeliefForCreature;
    public float divisorForAverageDesires;
    public float thresholdForAverageDesiresHelpSprites;
    public float alignmentChangePerDisciple;
    public float maxDistanceForTownForest;
    public int shuffleVillagersEvery;
    public float beliefSpeedScaleMultiPlayer;
    public float[] beliefSpeedScaleStory = new float[6];
    public float fightWonImpressiveValue;

    @Override
    public void read(EndianDataInputStream str) throws IOException {
        little(str);
        super.read(str);
        townType = str.readInt();
        size = str.readInt();
        minHousesToSetup = str.readInt();
        maxHousesToSetup = str.readInt();
        maxSizeInCells = str.readInt();
        distance = str.readInt();
        split = str.readInt();
        aroundCitadelStartAngle = str.readInt();
        aroundCitadelStepAngle = str.readInt();
        aroundCitadelStartDistance = str.readInt();
        aroundCitadelEndDistance = str.readInt();
        townCentre = str.readInt();
        storagePit = str.readInt();
        percentFemale = str.readInt();
        processAbodeEvery = str.readInt();
        newBuildingEvery = str.readInt();
        profession = readIntArray(str, profession);
        happyFoodMultiplier = str.readFloat();
        influence = str.readFloat();
        numberOfDaysFoodInStoreToBeHappy = str.readFloat();
        happyWoodPerBuildingSite = str.readFloat();
        playtimeEvery = str.readInt();
        maxDistanceWallBeBuilt = str.readFloat();
        beliefNeededForWonder = str.readFloat();
        proportionDeadForGraveyard = str.readFloat();
        playerInteactDecay = str.readFloat();
        howImpressedWithFlyingThing = str.readFloat();
        impressedWithFlyingThingRemovedAsSeen = str.readFloat();
        impressedWithFlyingThingAddPerGameTurn = str.readFloat();
        baseBeliefDesireValue = str.readFloat();
        totalWoodNeededToStartBuilding = str.readFloat();
        firstTimeDamageDoneAddition = str.readFloat();
        totalScaffoldNeededToStartBuilding = str.readInt();
        builtPercentBeforeWhichYouCanAddScaffolds = str.readFloat();
        beliefInNeutralPlayer = str.readFloat();
        maxAlignmentChangePerGameTurnForDesires = str.readFloat();
        storyInfluence = readFloatArray(str, storyInfluence);
        maxForTimeWillWorkUntil = str.readFloat();
        bedTimeMod = str.readFloat();
        foodWantedMultiplier = str.readFloat();
        minimumWoodForDesire = str.readFloat();
        maximumWoodForDesire = str.readFloat();
        numOfBuildingsForDesiredWood = str.readFloat();
        relaxationMod = str.readFloat();
        startingBeliefForCreatedTown = str.readFloat();
        emptyTownAllowedThisManyVillagers = str.readInt();
        multiplierForAddingResourceToTown = str.readFloat();
        multiplierForNonOwnerAddingResource = str.readFloat();
        maxGameturnsForBeliefAfterRemovingFromStoragePit = str.readInt();
        footballMatchDuration = str.readFloat();
        beliefForFooballMatch = str.readFloat();
        thresholdToStartRepairing = str.readFloat();
        gameTurnsAfterEmergencyVillagersReact = str.readInt();
        numSecondsToIgnoreCreature = str.readInt();
        numSecondsBeforeTownForgetsAboutCreature = str.readInt();
        maxDistanceForVillagersToGoToTheWorshipsite = str.readInt();
        minLifeForVillagersToGoToTheWorshipsite = str.readFloat();
        consideredEvilIfMakingDisciplesAndDesireIsLessThan = str.readFloat();
        consideredGoodIfMakingDisciplesAndDesireIsGreaterThan = str.readFloat();
        numGameTurnsBetweenGettingBeliefForArtifacts = str.readInt();
        populationForUnmodifiedBelief = str.readFloat();
        multiplierForBeliefFromVillagersDancingAroundArtifact = str.readFloat();
        giveResourceAligmnetChangeMultiplier = str.readFloat();
        takeResourceAligmnetChangeMultiplier = str.readFloat();
        maxDistanceFromCongreationPosThatPeopleChillOut = str.readFloat();
        maxDistanceFromHouseThatPeopleChillOut = str.readFloat();
        maxDistanceThatVillagersWillGoToWorship = str.readFloat();
        amountOverCapacityThatDiscipleBreedersBreedUntil = str.readFloat();
        populationUnderWhichHelpSpritesWarn = str.readInt();
        oneOffBeliefForCreature = str.readFloat();
        divisorForAverageDesires = str.readFloat();
        thresholdForAverageDesiresHelpSprites = str.readFloat();
        alignmentChangePerDisciple = str.readFloat();
        maxDistanceForTownForest = str.readFloat();
        shuffleVillagersEvery = str.readInt();
        beliefSpeedScaleMultiPlayer = str.readFloat();
        beliefSpeedScaleStory = readFloatArray(str, 6);
        fightWonImpressiveValue = str.readFloat();
    }

    @Override
    public void write(EndianDataOutputStream str) throws IOException {
        little(str);
        super.write(str);
        str.writeInt(townType);
        str.writeInt(size);
        str.writeInt(minHousesToSetup);
        str.writeInt(maxHousesToSetup);
        str.writeInt(maxSizeInCells);
        str.writeInt(distance);
        str.writeInt(split);
        str.writeInt(aroundCitadelStartAngle);
        str.writeInt(aroundCitadelStepAngle);
        str.writeInt(aroundCitadelStartDistance);
        str.writeInt(aroundCitadelEndDistance);
        str.writeInt(townCentre);
        str.writeInt(storagePit);
        str.writeInt(percentFemale);
        str.writeInt(processAbodeEvery);
        str.writeInt(newBuildingEvery);
        writeIntArray(str, profession);
        str.writeFloat(happyFoodMultiplier);
        str.writeFloat(influence);
        str.writeFloat(numberOfDaysFoodInStoreToBeHappy);
        str.writeFloat(happyWoodPerBuildingSite);
        str.writeInt(playtimeEvery);
        str.writeFloat(maxDistanceWallBeBuilt);
        str.writeFloat(beliefNeededForWonder);
        str.writeFloat(proportionDeadForGraveyard);
        str.writeFloat(playerInteactDecay);
        str.writeFloat(howImpressedWithFlyingThing);
        str.writeFloat(impressedWithFlyingThingRemovedAsSeen);
        str.writeFloat(impressedWithFlyingThingAddPerGameTurn);
        str.writeFloat(baseBeliefDesireValue);
        str.writeFloat(totalWoodNeededToStartBuilding);
        str.writeFloat(firstTimeDamageDoneAddition);
        str.writeInt(totalScaffoldNeededToStartBuilding);
        str.writeFloat(builtPercentBeforeWhichYouCanAddScaffolds);
        str.writeFloat(beliefInNeutralPlayer);
        str.writeFloat(maxAlignmentChangePerGameTurnForDesires);
        writeFloatArray(str, storyInfluence);
        str.writeFloat(maxForTimeWillWorkUntil);
        str.writeFloat(bedTimeMod);
        str.writeFloat(foodWantedMultiplier);
        str.writeFloat(minimumWoodForDesire);
        str.writeFloat(maximumWoodForDesire);
        str.writeFloat(numOfBuildingsForDesiredWood);
        str.writeFloat(relaxationMod);
        str.writeFloat(startingBeliefForCreatedTown);
        str.writeInt(emptyTownAllowedThisManyVillagers);
        str.writeFloat(multiplierForAddingResourceToTown);
        str.writeFloat(multiplierForNonOwnerAddingResource);
        str.writeInt(maxGameturnsForBeliefAfterRemovingFromStoragePit);
        str.writeFloat(footballMatchDuration);
        str.writeFloat(beliefForFooballMatch);
        str.writeFloat(thresholdToStartRepairing);
        str.writeInt(gameTurnsAfterEmergencyVillagersReact);
        str.writeInt(numSecondsToIgnoreCreature);
        str.writeInt(numSecondsBeforeTownForgetsAboutCreature);
        str.writeInt(maxDistanceForVillagersToGoToTheWorshipsite);
        str.writeFloat(minLifeForVillagersToGoToTheWorshipsite);
        str.writeFloat(consideredEvilIfMakingDisciplesAndDesireIsLessThan);
        str.writeFloat(consideredGoodIfMakingDisciplesAndDesireIsGreaterThan);
        str.writeInt(numGameTurnsBetweenGettingBeliefForArtifacts);
        str.writeFloat(populationForUnmodifiedBelief);
        str.writeFloat(multiplierForBeliefFromVillagersDancingAroundArtifact);
        str.writeFloat(giveResourceAligmnetChangeMultiplier);
        str.writeFloat(takeResourceAligmnetChangeMultiplier);
        str.writeFloat(maxDistanceFromCongreationPosThatPeopleChillOut);
        str.writeFloat(maxDistanceFromHouseThatPeopleChillOut);
        str.writeFloat(maxDistanceThatVillagersWillGoToWorship);
        str.writeFloat(amountOverCapacityThatDiscipleBreedersBreedUntil);
        str.writeInt(populationUnderWhichHelpSpritesWarn);
        str.writeFloat(oneOffBeliefForCreature);
        str.writeFloat(divisorForAverageDesires);
        str.writeFloat(thresholdForAverageDesiresHelpSprites);
        str.writeFloat(alignmentChangePerDisciple);
        str.writeFloat(maxDistanceForTownForest);
        str.writeInt(shuffleVillagersEvery);
        str.writeFloat(beliefSpeedScaleMultiPlayer);
        writeFloatArray(str, beliefSpeedScaleStory, 6);
        str.writeFloat(fightWonImpressiveValue);
    }
}
