package it.ld.bw.info;

import java.io.IOException;

import it.ld.utils.EndianDataInputStream;
import it.ld.utils.EndianDataOutputStream;

public class GVillagerInfo extends GLivingInfo {
	public TribeType tribeType;
	public int sex;
	public VillagerNumber villagerNumber;
	public int superMesh;
	public int childMeshHigh;
	public int childMeshMedium;
	public int childMeshLow;
	public int highDetail;
	public int stdDetail;
	public int lowDetail;
	public int primaryJob;
	public int secondaryJob;
	public float jobEfficency;
	public int startHavingSexAge;
	public int stopHavingSexAge;
	public int wantSexSpring;
	public int wantSexSummer;
	public int wantSexAutumn;
	public int wantSexWinter;
	public int timePregnantFor;
	public int lookForJobDelay;
	public int waitAtHome;
	public int restAtHomeTime;
	public float restAtHomeRestoresLifeBy;
	public float pregnancyChance;
	public int inheritence;
	public int boyGirlChance;
	public float aveageHeightOfAdult;
	public int maxFoodCarried;
	public int maxWoodCarried;
	public int minWoodToShowGraphic;
	public int minFoodToShowGraphic;
	public int maxTraderFoodCarried;
	public int maxTraderWoodCarried;
	public float woodUsedPerBuildCycle;
	public float repairAmount;
	public int jobSpeed;
	public float percentLazy;
	public float chantLifeRate;
	public int dyingTimeWithoutGraveyard;
	public int dyingTimeWithGraveyard;
	public int timeForFootballChance;
	public int footballWinGoalTime;
	public int footballLostGoalTime;
	public float lookAheadDistance;
	public int scaredStiffTime;
	public int waitForDinner;
	public int housewifeGossipTime;
	public int housewifeWaits;
	public float foodNurishmentMultiplier;
	public float gameTurnReducesFoodInBellyBy;
	public float hungryForFood;
	public float starvingForFood;
	public float happyWithFood;
	public float fullWithFood;
	public float hungerToLifeMultiplier;
	public float starvingToLifeMultiplier;
	public int foodReqiredForDinner;
	public int processChecksEvery;
	public int havingSexTime;
	public int dancingSpeed;
	public float[] ageToScale = new float[20];
	public int[] lAttractAnim = new int[3];
	public int[] lNeedAnim = new int[3];
	public float maxDistCarryFoodPit;
	public float maxDistCarryWoodPit;
	public int allowFaceSubstitution;
	public float damageThresholdToGoHome;
	public float damageThresholdToSleepUntil;
	public int numGameTurnsAfterAggressionInterestedInShield;
	public float pauseForASecondChance;
	public float baseForTownNeedsSpeedMod;
	public float divisorForTownNeedsSpeedMod;
	public float speedModWhenFullLoadOfWood;
	public float speedModWhenFullLoadOfFood;
	public float lifeWhenWalksWounded;
	public float lifeWhenCrawlsWounded;
	public int amountOfWoodPerBuilderWanted;
	public int keepMeshWhenChangeTown;
	public float ownDesireThreshold;
	public float maxDistanceFromArtifactDanceCanBe;
	public short initialChillOutTime;
	public short subsequentChillOutTime;
	public short timeToWaitForArtifactDance;
	public short drowningTime;
	public float foodPowerupIncrease;
	public float missionaryImpressiveValue;
	
	@Override
	public void read(EndianDataInputStream str) throws IOException {
		little(str);
		super.read(str);
		tribeType = TribeType.valueOf(str.readInt());
		sex = str.readInt();
		villagerNumber = VillagerNumber.valueOf(str.readInt());
		superMesh = str.readInt();
		childMeshHigh = str.readInt();
		childMeshMedium = str.readInt();
		childMeshLow = str.readInt();
		highDetail = str.readInt();
		stdDetail = str.readInt();
		lowDetail = str.readInt();
		primaryJob = str.readInt();
		secondaryJob = str.readInt();
		jobEfficency = str.readFloat();
		startHavingSexAge = str.readInt();
		stopHavingSexAge = str.readInt();
		wantSexSpring = str.readInt();
		wantSexSummer = str.readInt();
		wantSexAutumn = str.readInt();
		wantSexWinter = str.readInt();
		timePregnantFor = str.readInt();
		lookForJobDelay = str.readInt();
		waitAtHome = str.readInt();
		restAtHomeTime = str.readInt();
		restAtHomeRestoresLifeBy = str.readFloat();
		pregnancyChance = str.readFloat();
		inheritence = str.readInt();
		boyGirlChance = str.readInt();
		aveageHeightOfAdult = str.readFloat();
		maxFoodCarried = str.readInt();
		maxWoodCarried = str.readInt();
		minWoodToShowGraphic = str.readInt();
		minFoodToShowGraphic = str.readInt();
		maxTraderFoodCarried = str.readInt();
		maxTraderWoodCarried = str.readInt();
		woodUsedPerBuildCycle = str.readFloat();
		repairAmount = str.readFloat();
		jobSpeed = str.readInt();
		percentLazy = str.readFloat();
		chantLifeRate = str.readFloat();
		dyingTimeWithoutGraveyard = str.readInt();
		dyingTimeWithGraveyard = str.readInt();
		timeForFootballChance = str.readInt();
		footballWinGoalTime = str.readInt();
		footballLostGoalTime = str.readInt();
		lookAheadDistance = str.readFloat();
		scaredStiffTime = str.readInt();
		waitForDinner = str.readInt();
		housewifeGossipTime = str.readInt();
		housewifeWaits = str.readInt();
		foodNurishmentMultiplier = str.readFloat();
		gameTurnReducesFoodInBellyBy = str.readFloat();
		hungryForFood = str.readFloat();
		starvingForFood = str.readFloat();
		happyWithFood = str.readFloat();
		fullWithFood = str.readFloat();
		hungerToLifeMultiplier = str.readFloat();
		starvingToLifeMultiplier = str.readFloat();
		foodReqiredForDinner = str.readInt();
		processChecksEvery = str.readInt();
		havingSexTime = str.readInt();
		dancingSpeed = str.readInt();
		readFloatArray(str, ageToScale);
		lAttractAnim = readIntArray(str, lAttractAnim);
		lNeedAnim = readIntArray(str, lNeedAnim);
		maxDistCarryFoodPit = str.readFloat();
		maxDistCarryWoodPit = str.readFloat();
		allowFaceSubstitution = str.readInt();
		damageThresholdToGoHome = str.readFloat();
		damageThresholdToSleepUntil = str.readFloat();
		numGameTurnsAfterAggressionInterestedInShield = str.readInt();
		pauseForASecondChance = str.readFloat();
		baseForTownNeedsSpeedMod = str.readFloat();
		divisorForTownNeedsSpeedMod = str.readFloat();
		speedModWhenFullLoadOfWood = str.readFloat();
		speedModWhenFullLoadOfFood = str.readFloat();
		lifeWhenWalksWounded = str.readFloat();
		lifeWhenCrawlsWounded = str.readFloat();
		amountOfWoodPerBuilderWanted = str.readInt();
		keepMeshWhenChangeTown = str.readInt();
		ownDesireThreshold = str.readFloat();
		maxDistanceFromArtifactDanceCanBe = str.readFloat();
		initialChillOutTime = str.readShort();;
		subsequentChillOutTime = str.readShort();;
		timeToWaitForArtifactDance = str.readShort();;
		drowningTime = str.readShort();
		foodPowerupIncrease = str.readFloat();
		missionaryImpressiveValue = str.readFloat();
	}
	
	@Override
	public void write(EndianDataOutputStream str) throws IOException {
		throw new RuntimeException("Method not implemented");
	}
}
